---
version: '3.3'

services:
  nldi-db:
    image: ghcr.io/internetofwater/nldi-db:demo
    container_name: nldi-db
    environment:
      POSTGRES_PASSWORD: changeMe
      NLDI_DATABASE_ADDRESS: localhost
      NLDI_DATABASE_NAME: nldi
      NLDI_DB_OWNER_USERNAME: nldi
      NLDI_DB_OWNER_PASSWORD: changeMe
      NLDI_SCHEMA_OWNER_USERNAME: nldi_schema_owner
      NLDI_SCHEMA_OWNER_PASSWORD: changeMe
      NHDPLUS_SCHEMA_OWNER_USERNAME: nhdplus
      NLDI_READ_ONLY_USERNAME: read_only_user
      NLDI_READ_ONLY_PASSWORD: changeMe
    networks:
      - nldi
    volumes:
      - data:/var/lib/postgresql/data

  nldi-py:
    build:
      context: .
    container_name: nldi-py
    ports:
      - "8080:8080"
    environment:
      NLDI_PATH: /api/nldi
      NLDI_URL: http://localhost:8080/
      NLDI_DB_HOST: nldi-db
      NLDI_DB_PORT: 5432
      NLDI_DB_NAME: nldi
      NLDI_DB_USERNAME: nldi
      NLDI_DB_PASSWORD: changeMe
      PYGEOAPI_URL: https://labs.waterdata.usgs.gov/api/nldi/pygeoapi/
      springFrameworkLogLevel:
    networks:
      - nldi



networks:
  nldi:
volumes:
  data:
