#=================================================================
#
# Authors: Benjamin Webb <bwebb@lincolninst.edu
#
# Copyright (c) 2023 Ben Webb
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 80
  url: ${NLDI_URL}/pygeoapi #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  language: en-US
  cors: true
  pretty_print: true
  limit: 100
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: DEBUG
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: National Linked Data Index as OGC API - Features
    description: National Linked Data Index as OGC API - Features
    keywords:
      - geospatial
      - nldi
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/internetofwater/nldi-py
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Internet of Water
    url: https://github.com/internetofwater/nldi-py
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://internetofwater.org
    role: pointOfContact

resources:
  nhdplus/catchments:
    type: collection
    title: Catchments
    description: NHDPlus Catchments
    keywords:
      - catchments
      - nhd
      - vaa
    links: &nhdplus-links
      - type: application/html
        rel: canonical
        title: data source
        href: https://www.usgs.gov/national-hydrography/nhdplus-high-resolution
        hreflang: en-US
    extents: &nhdplus-extents
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - type: feature
        name: PostgreSQL
        data: &nhdplus-provider-data
          host: ${NLDI_DB_HOST}
          dbname: ${NLDI_DB_NAME}
          user: ${NLDI_DB_USERNAME}
          password: ${NLDI_DB_PASSWORD}
          search_path: [nhdplus]
        id_field: featureid
        table: catchmentsp
        geom_field: the_geom
  # nhdplus/megadiv:
  #   type: collection
  #   title: Catchments
  #   description: NHDPlus Catchments
  #   keywords:
  #     - catchments
  #     - nhd
  #     - vaa
  #   links: *nhdplus-links
  #   extents: *nhdplus-extents
  #   providers:
  #     - type: feature
  #       name: PostgreSQL
  #       data: *nhdplus-provider-data
  #       id_field: objectid
  #       table: medadiv_np21
  nhdplus/flowline:
    type: collection
    title: Flowlines
    description: NHDPlus Flowlines
    keywords:
      - flowlines
      - nhd
      - vaa
    links: *nhdplus-links
    extents: *nhdplus-extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *nhdplus-provider-data
        id_field: nhdplus_comid
        table: nhdflowline_np21
        geom_field: shape
  nhdplus/plusconnect:
    type: collection
    title: Plus Connect
    description: NHDPlus Connect
    keywords:
      - connect
      - nhd
      - vaa
    links: *nhdplus-links
    extents: *nhdplus-extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *nhdplus-provider-data
        id_field: objectid
        table: nhdplusconnect_np21
  nhdplus/flow:
    type: collection
    title: Flow
    description: NHDPlus Flow
    keywords:
      - connect
      - nhd
      - vaa
    links: *nhdplus-links
    extents: *nhdplus-extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *nhdplus-provider-data
        id_field: objectid
        table: plusflow_np21
  nhdplus/flowlinevaa:
    type: collection
    title: Flowline Value Added Attributes
    description: NHDPlus Flowline Value Added Attributes
    keywords:
      - flowlines
      - nhd
      - vaa
    links: *nhdplus-links
    extents: *nhdplus-extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *nhdplus-provider-data
        id_field: comid
        table: plusflowlinevaa_np21

  nldi/crawler_source:
    type: collection
    title: Crawler Source
    description: NLDI crawler source table
    keywords:
      - nldi
      - crawler
    links: *nhdplus-links
    extents: *nhdplus-extents
    providers:
      - type: feature
        name: PostgreSQL
        data: &nldi-provider-data
          host: ${NLDI_DB_HOST}
          dbname: ${NLDI_DB_NAME}
          user: ${NLDI_DB_USERNAME}
          password: ${NLDI_DB_PASSWORD}
          search_path: [nldi_data]
        id_field: crawler_source_id
        table: crawler_source
  nldi/features:
    type: collection
    title: Features
    description: NLDI Features indexed by the NLDI Crawler
    keywords:
      - nldi
      - features
    links: *nhdplus-links
    extents: *nhdplus-extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *nldi-provider-data
        id_field: identifier
        table: feature
        geom_field: location
  nldi/mainstem_lookup:
    type: collection
    title: Mainstem Lookup
    description: NLDI Mainstem Lookup
    keywords:
      - nldi
      - mainstem
    links: *nhdplus-links
    extents: *nhdplus-extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *nldi-provider-data
        id_field: nhdpv2_comid
        table: mainstem_lookup
